version: '3'
services:
  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: luisf/nginx
    container_name: nginx
    port:
      - "80:80"
    networks: 
      - production-network
    depends_on: 
      - "node1"
      - "node2"
      - "node3"
  
  mongodb:
    image: mongo
    networks: 
      - production-network
  
  node1:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: luisf/alura-books
    container_name: alura-books-1
    port:
      - "3000"
    networks: 
      - production-network
    depends_on: 
      - "mongodb"
  
  node2:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: luisf/alura-books
    container_name: alura-books-2
    port:
      - "3000"
    networks: 
      - production-network
    depends_on: 
      - "mongodb"

  node3:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: luisf/alura-books
    container_name: alura-books-3
    port:
      - "3000"
    networks: 
      - production-network
    depends_on: 
      - "mongodb"

networks: 
  production-network:
    driver: bridge